BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Registrations" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL,
	"Username"	TEXT NOT NULL,
	"Phone"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);
COMMIT;
